name: m12data
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  get_it: ^7.2.0
#  m12business:
#    path: ../m12business
  injectable: ^1.5.3

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  injectable_generator: ^1.5.3
  build_runner: ^2.1.11
